name: build
on:
    push:
        branches:
            - master
    pull_request:
        types:
            - opened
            - synchronize
        branches:
            - master
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node 12
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - run: yarn
            - run: yarn build
            - run: yarn test
              env:
                  CI: true
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1
              with:
                  token: ${{ secrets.CODE_COV_UPLOAD_TOKEN }}
                  directory: ./coverage/
                  flags: unittests
                  name: codecov-umbrella
                  fail_ci_if_error: true
                  path_to_write_report: ./coverage/codecov_report.gz
